/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SecondLifeRouteImport } from './routes/second-life'
import { Route as RescueRouteImport } from './routes/rescue'
import { Route as RelayCartRouteImport } from './routes/relay-cart'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as GenieRouteImport } from './routes/genie'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AmazonRouteImport } from './routes/amazon'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReturnsIndexRouteImport } from './routes/returns.index'
import { Route as AmazonIndexRouteImport } from './routes/amazon.index'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as ReturnsNewRouteImport } from './routes/returns.new'
import { Route as RescuePairsRouteImport } from './routes/rescue.pairs'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as LedgerUnitIdRouteImport } from './routes/ledger.$unitId'
import { Route as AmazonSellerRouteImport } from './routes/amazon.seller'
import { Route as AmazonOrdersRouteImport } from './routes/amazon.orders'
import { Route as AmazonCartRouteImport } from './routes/amazon.cart'
import { Route as AmazonProductsIdRouteImport } from './routes/amazon.products.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SecondLifeRoute = SecondLifeRouteImport.update({
  id: '/second-life',
  path: '/second-life',
  getParentRoute: () => rootRouteImport,
} as any)
const RescueRoute = RescueRouteImport.update({
  id: '/rescue',
  path: '/rescue',
  getParentRoute: () => rootRouteImport,
} as any)
const RelayCartRoute = RelayCartRouteImport.update({
  id: '/relay-cart',
  path: '/relay-cart',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const GenieRoute = GenieRouteImport.update({
  id: '/genie',
  path: '/genie',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AmazonRoute = AmazonRouteImport.update({
  id: '/amazon',
  path: '/amazon',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsIndexRoute = ReturnsIndexRouteImport.update({
  id: '/returns/',
  path: '/returns/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmazonIndexRoute = AmazonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AmazonRoute,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/seller/orders',
  path: '/seller/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsNewRoute = ReturnsNewRouteImport.update({
  id: '/returns/new',
  path: '/returns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RescuePairsRoute = RescuePairsRouteImport.update({
  id: '/pairs',
  path: '/pairs',
  getParentRoute: () => RescueRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerUnitIdRoute = LedgerUnitIdRouteImport.update({
  id: '/ledger/$unitId',
  path: '/ledger/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)
const AmazonSellerRoute = AmazonSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AmazonRoute,
} as any)
const AmazonOrdersRoute = AmazonOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AmazonRoute,
} as any)
const AmazonCartRoute = AmazonCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AmazonRoute,
} as any)
const AmazonProductsIdRoute = AmazonProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AmazonRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/amazon': typeof AmazonRouteWithChildren
  '/cart': typeof CartRoute
  '/genie': typeof GenieRoute
  '/impact': typeof ImpactRoute
  '/ops': typeof OpsRoute
  '/relay-cart': typeof RelayCartRoute
  '/rescue': typeof RescueRouteWithChildren
  '/second-life': typeof SecondLifeRoute
  '/wishlist': typeof WishlistRoute
  '/amazon/cart': typeof AmazonCartRoute
  '/amazon/orders': typeof AmazonOrdersRoute
  '/amazon/seller': typeof AmazonSellerRoute
  '/ledger/$unitId': typeof LedgerUnitIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/rescue/pairs': typeof RescuePairsRoute
  '/returns/new': typeof ReturnsNewRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/amazon/': typeof AmazonIndexRoute
  '/returns/': typeof ReturnsIndexRoute
  '/amazon/products/$id': typeof AmazonProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/genie': typeof GenieRoute
  '/impact': typeof ImpactRoute
  '/ops': typeof OpsRoute
  '/relay-cart': typeof RelayCartRoute
  '/rescue': typeof RescueRouteWithChildren
  '/second-life': typeof SecondLifeRoute
  '/wishlist': typeof WishlistRoute
  '/amazon/cart': typeof AmazonCartRoute
  '/amazon/orders': typeof AmazonOrdersRoute
  '/amazon/seller': typeof AmazonSellerRoute
  '/ledger/$unitId': typeof LedgerUnitIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/rescue/pairs': typeof RescuePairsRoute
  '/returns/new': typeof ReturnsNewRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/amazon': typeof AmazonIndexRoute
  '/returns': typeof ReturnsIndexRoute
  '/amazon/products/$id': typeof AmazonProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/amazon': typeof AmazonRouteWithChildren
  '/cart': typeof CartRoute
  '/genie': typeof GenieRoute
  '/impact': typeof ImpactRoute
  '/ops': typeof OpsRoute
  '/relay-cart': typeof RelayCartRoute
  '/rescue': typeof RescueRouteWithChildren
  '/second-life': typeof SecondLifeRoute
  '/wishlist': typeof WishlistRoute
  '/amazon/cart': typeof AmazonCartRoute
  '/amazon/orders': typeof AmazonOrdersRoute
  '/amazon/seller': typeof AmazonSellerRoute
  '/ledger/$unitId': typeof LedgerUnitIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/rescue/pairs': typeof RescuePairsRoute
  '/returns/new': typeof ReturnsNewRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/amazon/': typeof AmazonIndexRoute
  '/returns/': typeof ReturnsIndexRoute
  '/amazon/products/$id': typeof AmazonProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/amazon'
    | '/cart'
    | '/genie'
    | '/impact'
    | '/ops'
    | '/relay-cart'
    | '/rescue'
    | '/second-life'
    | '/wishlist'
    | '/amazon/cart'
    | '/amazon/orders'
    | '/amazon/seller'
    | '/ledger/$unitId'
    | '/products/$id'
    | '/rescue/pairs'
    | '/returns/new'
    | '/seller/orders'
    | '/amazon/'
    | '/returns/'
    | '/amazon/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/genie'
    | '/impact'
    | '/ops'
    | '/relay-cart'
    | '/rescue'
    | '/second-life'
    | '/wishlist'
    | '/amazon/cart'
    | '/amazon/orders'
    | '/amazon/seller'
    | '/ledger/$unitId'
    | '/products/$id'
    | '/rescue/pairs'
    | '/returns/new'
    | '/seller/orders'
    | '/amazon'
    | '/returns'
    | '/amazon/products/$id'
  id:
    | '__root__'
    | '/'
    | '/amazon'
    | '/cart'
    | '/genie'
    | '/impact'
    | '/ops'
    | '/relay-cart'
    | '/rescue'
    | '/second-life'
    | '/wishlist'
    | '/amazon/cart'
    | '/amazon/orders'
    | '/amazon/seller'
    | '/ledger/$unitId'
    | '/products/$id'
    | '/rescue/pairs'
    | '/returns/new'
    | '/seller/orders'
    | '/amazon/'
    | '/returns/'
    | '/amazon/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmazonRoute: typeof AmazonRouteWithChildren
  CartRoute: typeof CartRoute
  GenieRoute: typeof GenieRoute
  ImpactRoute: typeof ImpactRoute
  OpsRoute: typeof OpsRoute
  RelayCartRoute: typeof RelayCartRoute
  RescueRoute: typeof RescueRouteWithChildren
  SecondLifeRoute: typeof SecondLifeRoute
  WishlistRoute: typeof WishlistRoute
  LedgerUnitIdRoute: typeof LedgerUnitIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ReturnsNewRoute: typeof ReturnsNewRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  ReturnsIndexRoute: typeof ReturnsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/second-life': {
      id: '/second-life'
      path: '/second-life'
      fullPath: '/second-life'
      preLoaderRoute: typeof SecondLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rescue': {
      id: '/rescue'
      path: '/rescue'
      fullPath: '/rescue'
      preLoaderRoute: typeof RescueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relay-cart': {
      id: '/relay-cart'
      path: '/relay-cart'
      fullPath: '/relay-cart'
      preLoaderRoute: typeof RelayCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genie': {
      id: '/genie'
      path: '/genie'
      fullPath: '/genie'
      preLoaderRoute: typeof GenieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amazon': {
      id: '/amazon'
      path: '/amazon'
      fullPath: '/amazon'
      preLoaderRoute: typeof AmazonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/': {
      id: '/returns/'
      path: '/returns'
      fullPath: '/returns/'
      preLoaderRoute: typeof ReturnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amazon/': {
      id: '/amazon/'
      path: '/'
      fullPath: '/amazon/'
      preLoaderRoute: typeof AmazonIndexRouteImport
      parentRoute: typeof AmazonRoute
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/seller/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/new': {
      id: '/returns/new'
      path: '/returns/new'
      fullPath: '/returns/new'
      preLoaderRoute: typeof ReturnsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rescue/pairs': {
      id: '/rescue/pairs'
      path: '/pairs'
      fullPath: '/rescue/pairs'
      preLoaderRoute: typeof RescuePairsRouteImport
      parentRoute: typeof RescueRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger/$unitId': {
      id: '/ledger/$unitId'
      path: '/ledger/$unitId'
      fullPath: '/ledger/$unitId'
      preLoaderRoute: typeof LedgerUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amazon/seller': {
      id: '/amazon/seller'
      path: '/seller'
      fullPath: '/amazon/seller'
      preLoaderRoute: typeof AmazonSellerRouteImport
      parentRoute: typeof AmazonRoute
    }
    '/amazon/orders': {
      id: '/amazon/orders'
      path: '/orders'
      fullPath: '/amazon/orders'
      preLoaderRoute: typeof AmazonOrdersRouteImport
      parentRoute: typeof AmazonRoute
    }
    '/amazon/cart': {
      id: '/amazon/cart'
      path: '/cart'
      fullPath: '/amazon/cart'
      preLoaderRoute: typeof AmazonCartRouteImport
      parentRoute: typeof AmazonRoute
    }
    '/amazon/products/$id': {
      id: '/amazon/products/$id'
      path: '/products/$id'
      fullPath: '/amazon/products/$id'
      preLoaderRoute: typeof AmazonProductsIdRouteImport
      parentRoute: typeof AmazonRoute
    }
  }
}

interface AmazonRouteChildren {
  AmazonCartRoute: typeof AmazonCartRoute
  AmazonOrdersRoute: typeof AmazonOrdersRoute
  AmazonSellerRoute: typeof AmazonSellerRoute
  AmazonIndexRoute: typeof AmazonIndexRoute
  AmazonProductsIdRoute: typeof AmazonProductsIdRoute
}

const AmazonRouteChildren: AmazonRouteChildren = {
  AmazonCartRoute: AmazonCartRoute,
  AmazonOrdersRoute: AmazonOrdersRoute,
  AmazonSellerRoute: AmazonSellerRoute,
  AmazonIndexRoute: AmazonIndexRoute,
  AmazonProductsIdRoute: AmazonProductsIdRoute,
}

const AmazonRouteWithChildren =
  AmazonRoute._addFileChildren(AmazonRouteChildren)

interface RescueRouteChildren {
  RescuePairsRoute: typeof RescuePairsRoute
}

const RescueRouteChildren: RescueRouteChildren = {
  RescuePairsRoute: RescuePairsRoute,
}

const RescueRouteWithChildren =
  RescueRoute._addFileChildren(RescueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmazonRoute: AmazonRouteWithChildren,
  CartRoute: CartRoute,
  GenieRoute: GenieRoute,
  ImpactRoute: ImpactRoute,
  OpsRoute: OpsRoute,
  RelayCartRoute: RelayCartRoute,
  RescueRoute: RescueRouteWithChildren,
  SecondLifeRoute: SecondLifeRoute,
  WishlistRoute: WishlistRoute,
  LedgerUnitIdRoute: LedgerUnitIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  ReturnsNewRoute: ReturnsNewRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  ReturnsIndexRoute: ReturnsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
